Resolve VCSWP-20372 (TranscribeUtterance not generating as a PerclCommand)
FreeClimbAPI/nodejs-sdk pull request #64
Opened 2023-09-06 22:22 UTC by amahadaya

Closes VCSWP-20372

2023-09-06 22:38 UTC, katebrune commented on package.json
> +  "license": "Unlicense",
MIT

2023-09-06 22:42 UTC, katebrune commented on package.json
> +  "version": "3.5.1",
3.5.2

2023-09-06 23:03 UTC, katebrune approved these changes

2023-09-07 14:29 UTC, ngarg-vail requested changes

2023-09-07 15:01 UTC, ngarg-vail requested changes

2023-09-07 15:02 UTC, amahadaya commented on package.json
> +    "crypto": "^1.0.1"
I'll change this in the latest commit

2023-09-07 15:22 UTC, ngarg-vail approved these changes

2023-09-07 15:48 UTC, merged